version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"

    # This will hot reload the application
    volumes:
      - /app/node_modules
      - .:/app
