# name: Deploy Frontend
# on:
#   push:
#     branches:
#       - master

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
#       - run: docker build -t eliezerambion/react-test -f Dockerfile.dev .
#       - run: docker run -e CI=true eliezerambion/react-test npm test

name: Deploy Frontend
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout repo
      - uses: actions/checkout@v3

      # Login to Docker Hub (uses your secrets)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build test image from Dockerfile.dev
      - name: Build test image
        run: docker build -t eliezerambion/react-test -f Dockerfile.dev .

      # Run tests in container
      - name: Run tests
        run: docker run -e CI=true eliezerambion/react-test npm test
